source "https://rubygems.org"

gem "sinatra"
gem "haml"
gem "sequel"
gem "jdbc-mysql"
gem "require_all"
gem "sinatra-session"
gem "thread_safe"
gem "bcrypt"
gem "rufus-scheduler"
gem "eventmachine"
gem "faye-websocket"
gem "jruby_sandbox"